### PR TITLE
113 update modular context axioms and theorems

### PR DESCRIPTION
**Pull request by wdcraft01**
I think this is ready for review — meant to be a quick and brief update of the axiom(s) and theorems to the number/modular context, primarily consisting of transferring over and updating a number of theorems from the older theorems.py into the `_theorems_.ipynb`. The branch seems to be easily mergeable now back into master.

### CODE REVIEW

**Comment by wdcraft01** [comment]
I think I've now addressed the observations about the mod 0, extraneous comment(s), and SetOfAll formatting issue, and I've pushed the modifications to the 113- branch. Time for another review when you're ready.

**Comment by wdcraft01** [comment]
Wayne — Bob and I were both thinking that it makes sense to have a separate context for absolute value. We were wondering how the combination originally came about — perhaps because of the combination class ModAbs, perhaps, linking them? And for absolute value, are we actually thinking of the more “norm” in the case of complex numbers? If so, does something absolute_value informatively capture that? (i.e. is it generally understood that abs value would refer to a norm of a complex number?) Bob is ambivalent, thinking perhaps “absolute value” might be as good as we can get for a general term (there doesn't appear to be any separate nomenclature that “contains” both abs value and norm).

**Comment by wdcraft01** [comment]
Also, you know me in tending to prefer the longer names, since you asked — my natural inclination is for the longer absolute_value name but am fine with abs_val or abs_value. :o)

**Comment by wwitzel** [comment]
We can use "absolute_value" for the context name.  That's fine.  In using it, you'd just do
"from proveit.number import Abs"
so it isn't a big deal that it is actually contained in a package with a longer name.  It also serves as the norm of complex numbers.  That's pretty standard, and if Bob doesn't object, that's good enough for me.  Feel free to split this apart in the same branch, or do a different branch if you prefer -- either is fine with me.  There is also no harm in pulling a branch into master multiple times.  I haven't pulled it yet, but it wouldn't matter either way.

**Comment by wwitzel** [comment]
Why did they get lumped together in the first place?  I don't exactly remember.  It might have had to do with ModAbs, or it might have been due to the fact that "modulus" is another name of "absolute value".  But the latter would be a bad reason because it is mixing different concepts that happen to use similar names but are really different.

**Pull request merged**
