### PR TITLE
Craft edits containment demos

### PR DESCRIPTION
**Pull request by wdcraft01**
This is a complicated branch/pull-request due to the extent of the changes, but most of the _significant_ changes should merge pretty easily because they are mainly isolated from other system-wide work and are located primarily in the logic/set_theory/containment and logic/set_theory/enumeration contexts. This branch has not yet been rebased on top of current master.

The branch was originally created for establishing and developing the demonstrations page for the logic/set_theory/containment context (addressing things like ProperSubset, Subset, and SubsetEq classes and their superset counterparts). That original mission escalated to include the enumerated Set class and the logic/set_theory/enumeration context, leading to significant work in the enumerated Set methods and abstract_algebra/generic_methods.py code.

Although the branch lists around 167 changed files, a large number of these (~100) consist of theorem proof files (some empty, some with actual proofs).

Here is a brief summary of some of the more important changes, along with some related branch comments:

1. As an initial warning/acknowledgment: a handful of files (most notably expr.py, forall.py, implies.py, operation_over_instances.py, proof.py) appear to have considerable changes relative to master but the changes consist entirely or almost entirely of deletions of blank spaces. This might be an inadvertent result of something in my Sublime text editor and was unintentional.

2. The demonstrations page for the logic/set_theory/containment context has been significantly elaborated with demonstrations, along with substantial section for testing containment-related class methods.

3. The demonstrations page for the logic/set_theory/enumeration context has been significantly elaborated with demonstrations, along with substantial section for testing enumerated Set-related class methods.

4. The containment classes have been expanded and their methods expanded/elaborated. For example, while keeping the original Subset and Superset classes, the less ambiguously-named ProperSubset and ProperSuperset classes have been added, as have the negation containments such as NotProperSubset, NotSubsetEq, etc. You will see added functionality across many of the containment classes with additions of deduceInBool() methods and significant edits to the applyTransitivity() methods.

5. The enumerated Set class, along with the abstract_algebra/generic_methods.py, has been expanded to included significant new methods, including methods for deducing equality among permuted sets, and including a generic_permutation method in generic_methods for producing (and deriving equalities among) very general permutations of elements or operands by specifying an ordered list of element indices.

6. The enumerated Set class has also been augmented with deduceEnumProperSubset() and deduceEnumSubsetEq() methods, which seem to take up considerable code but seem to work well (i.e. efficiently and without relying much on automation). These deduction methods could readily be, but have not yet been, integrated into broader system automation. For example, the system will not currently automatically be able to execute something like Subset({1, 2}, {1, 2, 3}).prove(), but readily executes {1, 2, 3}.deduceEnumProperSubset(subset={1, 2}).

7. The enumerated Set class has also been augmented with Set.reduction() and Set.reduction_elem() methods for deducing equality between an enumerated Set and a reduced version of that same Set (i.e. eliminating multiplicities). Such reduction methods are then actively used in the deduceEnumSubset() methods.

8. The Or class (or_op.py) has been augmented with some initial efforts to establish three new methods: concludeViaLeft(), concludeViaSome(), and concludeViaPermutation(). The concludeViaSome() and concludeViaPermutation() methods still have some hard-coded constraints that can later be reworked to generalize better (for example, the code assumes the Or operands do not repeat).

9. Branch establishes the logic/set_theory/equivalence context and the associated SetEquiv class. The SetEquiv class was initially based on the Equals class and is only minimally developed, with Equals class code still included (commented out) for reference/consideration as we complete development of the Class and related methods.

### CODE REVIEW

**Comment by wdcraft01** [comment]
This is once again ready for a review. The craft_edits_containment_demos branch has successfully had the current master branch merged into it and the branch successfully makes it through the build.py --justessential, --justdemos, and --justproofs builds.

**Comment by wwitzel** [comment]
I couldn't get "--justproofs" to build because unfoldSubsetEq and unfoldSupsetEq respectively import "SubsetEqDef" and "SupersetEqDef" which should be "subsetEqDef" and "supersetEqDef".  I fixed those and am seeing if it will build now.

**Comment by wdcraft01** [comment]
That's somewhat bizarre. I don't understand how I could successfully run the --justproofs build then. Very puzzling. I see that I was in those proof notebook pages to update from specialize to instantiate …  so again very puzzling how they could have been running with that error. Sorry for the extra work on your end.

**Comment by wdcraft01** [comment]
So here is something interesting: I went back into this branch on my own computer (MacOS) and find that Python seems to be ignoring the capitalization of those axioms when importing. I include a screenshot of (a portion of) the proof notebook below just after restarting the kernel and running the notebook. My sense of reality is at least partially restored:

image

**Comment by wwitzel** [comment]
I'll add an issue to make sure we enforce case sensitivity.  We don't want this discrepancy in the future.  I'm sure it relates to the fact that importing from _common_, _axoms_, and _theorems_ works differently -- it is loading something from the file system rather than actually loading from a Python script directly.

**Pull request merged**
